gpt_model: "gpt-4-vision-preview"
# gpt_model: "gpt-4-1106-preview"
# gpt_model: "gpt-3.5-turbo-1106"

save_response: True
multiple_queries: True
use_txt: True
use_video: False

## STACK ##
# env_name: Stack
# txt_filename: Stack*
# video_filename: Stack*
# resize_frames: 256
# frame_step: 2

## LIFT ##
# env_name: Lift
# txt_filename: Lift*
# video_filename: Lift*
# resize_frames: 256

##  PICKNPLACE   ##
env_name: PickPlace
txt_filename: PickPlace*
video_filename: PickPlace&
frame_step: 3
resize_frames: 256

##  OPEN DOOR   ##
# env_name: Door
# txt_filename: Door*
# video_filename: Door*
# frame_step: 3
# resize_frames: 256

##  TOOL HANG  ##
# gpt_model: "gpt-4-vision-preview"
# env_name: tool_hang
# multiple_queries: False
# n_queries: 10
# N_TXT_STEPS: 680
# N_FRAME_STEPS: 137
# use_txt: True
# txt_step: 1
# txt_filename: tool_hang.txt
# use_video: True
# video_filename: robomimic/tool_hang/tool_hang_annotated.mp4
# frame_step: 10
# resize_frames: 256

##  TRANSPORT ##
# gpt_model: "gpt-4-vision-preview"
# env_name: transport
# use_txt: True
# txt_step: 1
# txt_filename: transport.txt
# use_video: True
# video_filename: robomimic/transport/transport_annotated.mp4
# frame_step: 20
# resize_frames: 256