gpt_model: "gpt-4-vision-preview"
# gpt_model: "gpt-4-1106-preview"
# gpt_model: "gpt-3.5-turbo-1106"

save_response: True
multiple_queries: True

## STACK ##
env_name: Stack
txt_filename: Stack*
video_filename: Stack*
use_txt: True
use_video: True
frame_step: 2
resize_frames: 256

## LIFT ##
# gpt_model: "gpt-4-vision-preview"
# env_name: lift
# use_txt: True
# txt_filename: lift.txt
# use_video: True
# video_filename: lift
# frame_step: 2
# resize_frames: 256

##  PICKNPLACE   ##
# gpt_model: "gpt-4-vision-preview"
# env_name: picknplace
# use_txt: True
# txt_filename: picknplace.txt
# use_video: True
# video_filename: picknplace
# frame_step: 10
# resize_frames: 256

##  OPEN DOOR   ##
# gpt_model: "gpt-4-vision-preview"
# env_name: open_door
# use_txt: True
# txt_filename: open_door.txt
# use_frames: True
# frames: open_door
# frame_step: 2
# resize_frames: 256
# save_response: True

##  TOOL HANG  ##
# gpt_model: "gpt-4-vision-preview"
# env_name: tool_hang
# multiple_queries: False
# n_queries: 10
# N_TXT_STEPS: 680
# N_FRAME_STEPS: 137
# use_txt: True
# txt_step: 1
# txt_filename: tool_hang.txt
# use_video: True
# video_filename: robomimic/tool_hang/tool_hang_annotated.mp4
# frame_step: 10
# resize_frames: 256

##  TRANSPORT ##
# gpt_model: "gpt-4-vision-preview"
# env_name: transport
# use_txt: True
# txt_step: 1
# txt_filename: transport.txt
# use_video: True
# video_filename: robomimic/transport/transport_annotated.mp4
# frame_step: 20
# resize_frames: 256