# gpt_model: "gpt-4-vision-preview"
gpt_model: "gpt-4-1106-preview"
# gpt_model: "gpt-3.5-turbo-1106"

# gpt_model: "gpt-4-vision-preview"
# use_txt: True
# txt_filename: picknplace.txt
# use_frames: True
# frames: picknplace
# frame_step: 25
# resize_frames: 256
# save_response: True

gpt_model: "gpt-4-vision-preview"
env_name: tool_hang

use_txt: True
start_txt_idx: 0
end_txt_idx: 100
txt_step: 10
txt_filename: tool_hang.txt

use_video: True
video_filename: robomimic/tool_hang/tool_hang_annotated.mp4
frame_step: 5
start_frame: 120
end_frame: 137
resize_frames: 256
save_response: True