# gpt_model: "gpt-4-vision-preview"
gpt_model: "gpt-4-1106-preview"
# gpt_model: "gpt-3.5-turbo-1106"

# gpt_model: "gpt-4-vision-preview"
# use_txt: True
# txt_filename: picknplace.txt
# use_frames: True
# frames: picknplace
# frame_step: 25
# resize_frames: 256
# save_response: True

# gpt_model: "gpt-4-vision-preview"
use_txt: True
txt_filename: tool_hang.txt
txt_step: 10
# use_video: True
# video_filename: robomimic/tool_hang/tool_hang_annotated.mp4
frame_step: 10
resize_frames: 256
save_response: True