###### LLM Options (Choose One) ######
# llm_model: "gpt-4-vision-preview"
# llm_model: "gpt-4-1106-preview"
# llm_model: "gpt-3.5-turbo-1106"
# llm_model: "gemini-pro"
llm_model: "gemini-pro-vision"

###### Environment Options (Choose One) ######
env_name: Door # Stack Lift PickPlace Door NutAssemblySquare ToolHang

multiple_queries: False # Query on all files according to llm_model and env_name

### When calling invidiual files, you have to specify the file name:
# robot_traj_runid: <env_name>_<data>-time_<>
robot_traj_runid: Door_20240213-183948_0
video_filename: Door_20240213-183948_0.mp4
textual_filename: Door_20240213-183948_0.txt

# Input Modality to the LLM
in_context: True
textual_input: False
video_input: True
save_response: True

# Data Slicing Options
resize_frames: 256
frame_step: 5
txt_step: 1
