###### LLM Options (Choose One) ######
llm_model: "gpt-4-vision-preview"
# llm_model: "gpt-4-1106-preview"
# llm_model: "gpt-3.5-turbo-1106"
# llm_model: "gemini-pro"
# llm_model: "gemini-pro-vision" # ONLY ACCEPTING 16 IMAGES AT THIS TIME :(

###### Environment Options (Choose One) ######
env_name: NutAssemblySquare # Stack Lift PickPlace Door NutAssemblySquare ToolHang

multiple_queries: True # Query on all files according to llm_model and env_name

### When calling invidiual files, you have to specify the file name:
# robot_traj_runid = <env_name>_<data>-time_<>

# Input Modality to the LLM
textual_input: True
video_input: True
save_response: True

# Data Slicing Options
resize_frames: 256
frame_step: 10
txt_step: 1
